name: Deploy Express Server to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch
    paths:
      - 'server/**'  # Trigger only when changes occur in the server directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ec2-52-91-174-152.compute-1.amazonaws.com >> ~/.ssh/known_hosts
        ssh-keygen -R ec2-52-91-174-152.compute-1.amazonaws.com
    - name: Deploy to AWS EC2
      run: |
        rsync -avz --exclude 'node_modules/' --exclude '.env' ./server/ ubuntu@ec2-52-91-174-152.compute-1.amazonaws.com::/opt/server
        ssh ubuntu@ec2-52-91-174-152.compute-1.amazonaws.com 'cd /opt/server && npm install --production && pm2 restart all'

    - name: Verify deployment
      run: |
        echo "Deployment completed successfully."
